apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  #change to chal name
  name: money-printer2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
    image: eu.gcr.io/sdctf-307600/money-printer2-healthcheck:1797959630837904011c227dce4cdfe082e5a7a93bbac79e63c401e09db582a9
  image: eu.gcr.io/rctf-379820/money-printer2-challenge:9c5892177c467218c7e892e3d80631ae276b4af351056924b6c8360566022ba3
