apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  #change to chal name
  name: tropic-thunder
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
    image: eu.gcr.io/sdctf-307600/tROPic-thunder-healthcheck:1797959630837904011c227dce4cdfe082e5a7a93bbac79e63c401e09db582a9
  image: eu.gcr.io/rctf-379820/tropic-thunder-challenge:0c264526b7668933d7cef996549360872c8df15d5fcb40b09b95bd25d6ef1def
