apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  #change to chal name
  name: open-sesame
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/rctf-379820/open-sesame-challenge:19573d12bdb2f9b5327e0ee49b471e2baccc46e76d34e85284c88fe8f741ce00
